// examples/vue/src/CameraExample.vue
<script setup>
import { ref } from "vue";
import { useMIG } from "motion-input-grid/vue";

const props = defineProps({ profileMode: Boolean });
const error = ref("");
const { state, video, canvas, start, stop, recalibrate, importJSON } = useMIG({
    assetBase: new URL("mig/", document.baseURI).href,
    profileMode: props.profileMode,
    onAction: event => console.log(event)
});

async function importProfile(event) {
    const file = event.target.files[0];
    event.target.value = "";
    if (!file) return;
    try {
        if (file.size > 1024 * 1024) throw new Error("Configuration exceeds 1 MiB");
        await importJSON(await file.text());
        error.value = "";
    } catch (failure) {
        error.value = failure.message;
    }
}
</script>

<template>
    <main>
        <h1>{{ props.profileMode ? "Run your MIG profile" : "Raise either hand" }}</h1>
        <p>Keep shoulders visible. Lower hands, then raise a wrist from green into yellow.</p>
        <nav aria-label="Examples">
            <a href="./index.html">Raised hands</a><a href="./profile.html">Import profile</a>
        </nav>
        <div class="controls">
            <button :disabled="state.busy || state.running" @click="start">Start camera</button>
            <button :disabled="!state.busy && !state.running" @click="stop">Stop</button>
            <button :disabled="!state.running" @click="recalibrate">Recalibrate</button>
            <label v-if="props.profileMode" class="file-button">Import JSON
                <input type="file" accept=".json,application/json" @change="importProfile">
            </label>
        </div>
        <p role="status">{{ state.status }}</p>
        <p v-if="error" role="alert">{{ error }}</p>
        <div class="actions" aria-live="polite">
            <span v-if="!state.actions.length">Waiting for a motion...</span>
            <div v-for="event in state.actions" :key="event.id">
                {{ !props.profileMode && ['left_raise', 'right_raise'].includes(event.action)
                    ? `${event.action.startsWith('left') ? 'Left' : 'Right'} hand raised!`
                    : `Action: ${event.action} (input ${event.id})` }}
            </div>
        </div>
        <div class="camera"><video ref="video" muted playsinline /><canvas ref="canvas" /></div>
    </main>
</template>

// examples/react/src/CameraExample.jsx
"use client";

import React, { useState } from "react";
import { useMIG } from "motion-input-grid/react";

export function CameraExample({ profileMode = false,
    handsHref = "./index.html", profileHref = "./profile.html" }) {
    const [error, setError] = useState("");
    const assetBase = typeof window === "undefined"
        ? undefined : new URL("mig/", document.baseURI).href;
    const mig = useMIG({ assetBase, profileMode, onAction: event => console.log(event) });

    async function importProfile(event) {
        const file = event.target.files[0];
        event.target.value = "";
        if (!file) return;
        try {
            if (file.size > 1024 * 1024) throw new Error("Configuration exceeds 1 MiB");
            await mig.importJSON(await file.text());
            setError("");
        } catch (failure) {
            setError(failure.message);
        }
    }

    return <main>
        <h1>{profileMode ? "Run your MIG profile" : "Raise either hand"}</h1>
        <p>Keep your shoulders visible. Lower your hands, then raise a wrist from green into yellow.</p>
        <nav aria-label="Examples">
            <a href={handsHref}>Raised hands</a><a href={profileHref}>Import profile</a>
        </nav>
        <div className="controls">
            <button onClick={mig.start} disabled={mig.busy || mig.running}>Start camera</button>
            <button onClick={mig.stop} disabled={!mig.busy && !mig.running}>Stop</button>
            <button onClick={mig.recalibrate} disabled={!mig.running}>Recalibrate</button>
            {profileMode && <label className="file-button">Import JSON
                <input type="file" accept=".json,application/json" onChange={importProfile} />
            </label>}
        </div>
        <p role="status">{mig.status}</p>
        {error && <p role="alert">{error}</p>}
        <div className="actions" aria-live="polite">
            {mig.actions.length === 0 ? "Waiting for a motion..." : mig.actions.map(event =>
                <div key={event.id}>{!profileMode && ["left_raise", "right_raise"].includes(event.action)
                    ? `${event.action.startsWith("left") ? "Left" : "Right"} hand raised!`
                    : `Action: ${event.action} (input ${event.id})`}</div>)}
        </div>
        <div className="camera">
            <video ref={mig.video} muted playsInline /><canvas ref={mig.canvas} />
        </div>
    </main>;
}
